// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvoho7qf-gYLfvJjYtX275SSBfHiIXa6I',
    appId: '1:54035457595:android:4ed3c32b63dbb1566a5e1e',
    messagingSenderId: '54035457595',
    projectId: 'backstage-inventory',
    storageBucket: 'backstage-inventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJmJePPEHuVPzzYTC6i48MosDF3dqh0zE',
    appId: '1:54035457595:ios:7501a2ef83bee3056a5e1e',
    messagingSenderId: '54035457595',
    projectId: 'backstage-inventory',
    storageBucket: 'backstage-inventory.firebasestorage.app',
    androidClientId: '54035457595-drudqk28p39jtqv4s8jl6n92mhr4edgu.apps.googleusercontent.com',
    iosClientId: '54035457595-2ukdqo6gjujogu7s3ssilpt7j0b6j0hr.apps.googleusercontent.com',
    iosBundleId: 'com.backstage.backlog',
  );

}